### ISSUE TITLE
terminal errors: permission denied

### ISSUE THREAD

**Issue by chhschou** [zplugin/z-a-bin-gem-node#1]
Hi @psprint I tried installing this as recommended from https://github.com/zdharma/zplugin/issues/177

I first did `zplugin self-update` then added `zplugin light zplugin/z-a-bin-gem-node` before first plugin definition. 

Upon starting a brand new terminal, the `z-a-bin-gem-node` is cloned but immediately follows these errors:

-zplg-load-plugin:40: permission denied:
-zplg-load-plugin:40: permission denied:
-zplg-load-plugin:40: permission denied:
-zplg-load-plugin:40: permission denied:
-zplg-load-plugin:40: permission denied:
-zplg-load-plugin:40: permission denied:
-zplg-load-plugin:40: permission denied:
-zplg-load-plugin:40: permission denied:
-zplg-load-plugin:40: permission denied:
-zplg-load-plugin:85: permission denied:
-zplg-load-plugin:85: permission denied:
-zplg-load-plugin:85: permission denied:
-zplg-load-plugin:40: permission denied:
-zplg-load-plugin:40: permission denied:
-zplg-load-plugin:40: permission denied:
-zplg-load-plugin:85: permission denied:
-zplg-load-plugin:85: permission denied:
-zplg-load-plugin:85: permission denied:
-zplg-load-plugin:85: permission denied:
-zplg-load-plugin:85: permission denied:
-zplg-load-plugin:85: permission denied:
-zplg-load-plugin:40: permission denied:
-zplg-load-plugin:40: permission denied:
-zplg-load-plugin:40: permission denied:
-zplg-load-plugin:40: permission denied:
-zplg-load-plugin:40: permission denied:
-zplg-load-plugin:40: permission denied:
-zplg-load-snippet:130: permission denied:
-zplg-load-snippet:130: permission denied:
-zplg-load-snippet:130: permission denied:

**Comment by psprint** [comment]
Could you add the line:

```zsh
print -rl "ARR: $arr" "KEY:$key" "ZPLG_EXTS[\$key]:${ZPLG_EXTS[$key]}" >> /tmp/zplugin.txt
```
at the line number 1291, here:

```zsh
for key in "${reply[@]}"; do
    arr=( "${(Q)${(z@)ZPLG_EXTS[$key]}[@]}" )
    "${arr[5]}" "plugin" "$user" "$plugin" "$id_as" "$pdir_orig" \!atload
    print -rl "ARR: $arr" "KEY:$key" "ZPLG_EXTS[\$key]:${ZPLG_EXTS[$key]}" >> /tmp/zplugin.txt # should be line 1291 in zplugin.zsh
done                                 
```
to the file `~/.zplugin/bin/zplugin.zsh`, then start a new shell, and attach the file `/tmp/zplugin.txt`?

**Comment by psprint** [comment]
Any chances for update on this?

**Comment by psprint** [comment]
If the request is too complex, then could the following be done:

```zsh
autoload allopt
allopt > allopt.txt
```

and then the file allopt.txt attached here?

**Comment by chhschou** [comment]
Sorry I got pulled away on a couple of things. I had some other build problem with system, and after correcting those the error with this disappeared.

**Comment by psprint** [comment]
Thanks. The errors were so specific, that I've became very worried about some configuration of Zshell that makes the code that splits the strings incorrect. Because of this, is there a chance of getting the `allopt.txt` file attached? It might help me in future when such problem could go back.

**Comment by chhschou** [comment]
[allopt.txt](https://github.com/zplugin/z-a-bin-gem-node/files/3818650/allopt.txt)
[allopt_good.txt](https://github.com/zplugin/z-a-bin-gem-node/files/3818856/allopt_good.txt)
I got the issue again but the error is different this time. It is basically caused by me using a package manager called `spack` to install libraries required for building system packages like libicov. 

In the attached files the allopt_good.txt is the one that works, allopt.txt is the when I'm getting errors. Looks like `shwordsplit` is on when I'm getting errors:
```
-zplg-load-plugin:53: permission denied: 
-zplg-load-plugin:53: permission denied: 
-zplg-load-plugin:102: permission denied: 
-zplg-load-plugin:102: permission denied: 
-zplg-load-plugin:102: permission denied: 
-zplg-load-plugin:102: permission denied: 
-zplg-load-plugin:102: permission denied: 
-zplg-load-plugin:102: permission denied: 
-zplg-load-snippet:132: permission denied: 
-zplg-load-snippet:132: permission denied: 
-zplg-load-snippet:132: permission denied: 
-zplg-load-snippet:132: permission denied: 
-zplg-load-snippet:132: permission denied: 
-zplg-load-snippet:132: permission denied: 
-zplg-load-snippet:132: permission denied: 
-zplg-load-snippet:132: permission denied: 
-zplg-load-snippet:132: permission denied: 
-zplg-load-snippet:132: permission denied: 
-zplg-load-snippet:132: permission denied: 
-zplg-load-snippet:132: permission denied: 
-zplg-load-plugin:102: permission denied: 
-zplg-load-plugin:102: permission denied: 
-zplg-load-plugin:102: permission denied: 

```

**Comment by psprint** [comment]
Thank you. I've pushed the fix.

**Comment by chhschou** [comment]
Thanks it works well
