### ISSUE TITLE
Automatically `chmod +x` the files?

### ISSUE THREAD

**Issue by lainiwa** [zplugin/z-a-bin-gem-node#2]
If we `fbin''`/`sbin''` a binary release, which is either

1. not archived
2. or archived in a format, which does not preserve permission flags

we will not be able to execute the file before somehow explicitly adding the execution permission.

Example:
```sh
zplugin ice from"gh-r" bpick"^ffsend-v*-linux-x64-static$" \
    mv"ffsend-* -> ffsend" fbin"ffsend"
zplugin load timvisee/ffsend

ffsend
```
fails with `permission denied` error.

**Comment by psprint** [comment]
True, that's an issue. I'll fix it, thanks!

**Comment by psprint** [comment]
Ok, it should now be fixed. The `+x` is given in the moment of the clone.

**Comment by psprint** [comment]
n/p
