### ISSUE TITLE
Allow path dependent ices to match patterns

### ISSUE THREAD

**Issue by NICHOLAS85** [zplugin/z-a-bin-gem-node#4]
For example `sbin'*/micro'` which currently doesn't function. Similar to how the `pick''` ice can accept patterns.

**Comment by psprint** [comment]
Ok, it's implemented for `sbin`. Thanks!

**Comment by psprint** [comment]
Also now all the results of the `sbin` substitution are handled, not only the first one.

**Comment by NICHOLAS85** [comment]
Looks like it's working correctly on my end, thanks!
